export const PLAY_NOT_EXIST = 'PLAY_NOT_EXIST';
export const PLAY_NOT_ENOUGH_SEATS = 'PLAY_NOT_ENOUGH_SEATS';
export const PLAY_IS_BOOKED = 'PLAY_IS_BOOKED';

export const TICKET_NOT_EXIST = 'TICKET_NOT_EXIST';
export const TICKET_UPDATE_ERROR = 'TICKET_UPDATE_ERROR';

export const BAD_REQUEST = 'BAD_REQUEST';
export const VALIDATION_ERROR = 'VALIDATION_ERROR';

export const NOT_AUTHORIZED = 'NOT_AUTHORIZED';
export const TOKEN_REVOKED = 'TOKEN_REVOKED';
